apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins
  labels:
    app: jenkins
spec:
  type: NodePort
  ports:
    # Jenkins UI
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30808  # Access via localhost:30808
      protocol: TCP
    
    # JNLP port for agents
    - name: jnlp
      port: 50000
      targetPort: 50000
      protocol: TCP
  
  selector:
    app: jenkins