apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-artifacts
  namespace: ml-pipeline
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 100Gi