apiVersion: v1 
kind: Service
metadata:
  name: {{ .Values.mongodb.name }}
  namespace: {{ .Values.mongodb.namespace }}
spec:
  clusterIP: None
  selector:
    app: {{ .Values.mongodb.name }}
  ports:
    - port: {{ .Values.mongodb.service.port }}
      targetPort: {{ .Values.mongodb.service.targetPort }}
      name: mongodb