{{- if .Values.storage.createStorageClass }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storage.storageClassName }}
  annotations:
    storageclass.kubernetes.io/is-default-class: {{ .Values.storage.isDefault | quote }}
provisioner: {{ .Values.storage.provisioner }}
volumeBindingMode: {{ .Values.storage.volumeBindingMode }}
reclaimPolicy: {{ .Values.storage.reclaimPolicy }}
allowVolumeExpansion: {{ .Values.storage.allowVolumeExpansion }}
{{- end }}