apiVersion: v1
kind: Service
metadata:
  name: ml-api
  namespace: ml-pipeline
spec:
  selector:
    app: ml-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
  type: ClusterIP