mongodb:
  replicas: 3
  resources:
    requests:
      memory: "4Gi"
      cpu: "2"
  storage:
    size: 50Gi

redis:
  replicas: 2
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1"

mlApi:
  replicas: 5
  resources:
    requests:
      memory: "1Gi"
      cpu: "1"
    limits:
      memory: "2Gi"
      cpu: "2"

mlTraining:
  resources:
    requests:
      memory: "8Gi"
      cpu: "4"
    limits:
      memory: "16Gi"
      cpu: "8"
  pvc:
    size: 100Gi

models:
  pvc:
    size: 200Gi